import os
import shutil
import subprocess
import time
from pathlib import Path
from typing import Union

import pytest

from e2e.mock_openai_server.server import FIXTURE_PATH


@pytest.fixture(autouse=True, scope="session")
def mock_openai_server():
    os.environ["OPENAI_BASE_URL"] = "http://localhost:8000/v1"

    proc = subprocess.Popen(
        ["python", "e2e/mock_openai_server/server.py"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    # Wait briefly for the server to start
    time.sleep(1)

    yield  # Test session runs here

    # Teardown
    proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()


def _ensure_fixture_file_exists():
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not FIXTURE_PATH.exists():
        FIXTURE_PATH.write_text(
            "// Do not edit this file manually, it is generated by the test suite.\n"
        )


def _copy_fixture(path: Path):
    if not path.exists():
        raise FileNotFoundError(f"Fixture not found: {path}")
    shutil.copyfile(path, FIXTURE_PATH)


@pytest.fixture()
def use_fixture():
    def _use_fixture(path: Union[str, Path]):
        if isinstance(path, str):
            path = Path(path)
        print(f"Using fixture: {path.absolute()}")
        _ensure_fixture_file_exists()
        _copy_fixture(path)

    fixture_path_absoulte = FIXTURE_PATH.absolute()
    yield _use_fixture
    fixture_path_absoulte.write_text(
        "// Do not edit this file manually, it is generated by the test suite.\n"
    )
