title: Fellow
description: Fellow is a command-line AI assistant built by developers, for developers.
remote_theme: just-the-docs/just-the-docs
logo: "/img/logo.svg"
favicon_ico: "/img/favicon.ico"
baseurl: "/fellow"
search_enabled: true
search.tokenizer_separator: /[\s/]+/
include:
  - docs